[package]

name = "iron-test"
version = "0.0.4"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Mocking suite for Iron requests."
repository = "https://github.com/reem/iron-test"
license = "MIT"

[dependencies]
iron = "*"
hyper = "*"
uuid = "*"
url = "*"

[dependencies.intovec]
git = "https://github.com/aleksandrpak/rust-intovec.git"
